ikg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

store/urls.py
from django.urls import path

from . import views


app_name = 'store'
urlpatterns = [
    path('', views.ProductsList.as_view(), name='list_products'),
    path('products/create', views.ProductsCreate.as_view(), name='create_product'),
    path('product/<slug:slug>', views.ProductsDetail.as_view(), name='view_product'),
    path('product/<slug:slug>/update', views.ProductsUpdate.as_view(), name='update_product'),
    path('product/<slug:slug>/delete', views.ProductsDelete.as_view(), name='delete_product'),
    path('product/<slug:slug>/mgmt_distributions', views.ProductsMgmtDistributions.as_view(), name='mgmt_product_distributions'),
    path('product/<slug:pslug>/toggle_distributor/<slug:dslug>', views.ProductsToggleDistributor.as_view(), name='toggle_product_distributor'),

    path('orders', views.OrdersList.as_view(), name='list_orders'),
    path('orders/create', views.OrdersCreate.as_view(), name='create_order'),
    path('order/<int:id>', views.OrdersDetail.as_view(), name='view_order'),
]

store/models.py
from django.db import models


class Distributor(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32, primary_key=True)

    class Meta:
        ordering = ('slug',)

    def __repr__(self):
        return '<Distributor {0}: {1}>'.format(self.slug, self.name)


class Product(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32, primary_key=True)
    category = models.CharField(max_length=32)
    price = models.IntegerField()
    description = models.CharField(max_length=200, blank=True)
    active = models.BooleanField(default=True)
    distributors = models.ManyToManyField(Distributor)

    class Meta:
        indexes = [
            models.Index(fields=['category'], name='category_idx'),
        ]
        ordering = ('category', 'slug',)

    def __repr__(self):
        return '<Product {0}: {1}>'.format(self.slug, self.name)


class Order(models.Model):
    deadline = models.DateTimeField(blank=True)
    note = models.CharField(max_length=200, blank=True)
    fee = models.IntegerField(blank=True)
    paid = models.BooleanField(default=False)
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    distributor = models.ForeignKey('Distributor', on_delete=models.SET_NULL, null=True)

    class Meta:
        indexes = [
            models.Index(fields=['deadline'], name='deadline_idx'),
            models.Index(fields=['paid'], name='paid_idx'),
        ]
        ordering = ('deadline',)

    def __repr__(self):
        return '<Order #{0}: {1}>'.format(self.id, self.product.name)

store/forms.py
from django.forms import ChoiceField, Textarea, ModelForm, ModelChoiceField

from store.models import Order, Product, Distributor


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('slug', 'name', 'category', 'price', 'description',)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = Textarea({'rows': 3})
        for field_name in self.fields:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})

        # Make `slug` attribute uneditable
        if self.instance.slug != '':
            del self.fields['slug']


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ('product', 'distributor', 'paid', 'fee', 'deadline', 'note',)

    def __init__(self, product=None, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        if product is not None:
            self.fields['product'].initial=product
            self.fields['distributor'] = ModelChoiceField(
                queryset=Distributor.objects.filter(product=product),
            )
        self.fields['note'].widget = Textarea({'rows': 3})
        for field_name in self.fields:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})

store/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.forms import ModelChoiceField

from .models import Distributor, Order, Product
from .forms import OrderForm, ProductForm


class ProductsList(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'all_products'

    def get_queryset(self):
        return Product.objects.all()


class ProductsCreate(generic.CreateView):
    form_class = ProductForm
    success_url = reverse_lazy('store:list_products')
    template_name = 'products/create.html'


class ProductsDetail(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'


class ProductsMgmtDistributions(generic.TemplateView):
    template_name = 'products/distribution_mgmt.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = get_object_or_404(Product, slug=kwargs['slug'])
        related_distributors = product.distributors.all()
        unrelated_distributors = Distributor.objects.exclude(slug__in=related_distributors.values('slug')).all()
        context['product'] = product
        context['related_distributors'] = related_distributors
        context['unrelated_distributors'] = unrelated_distributors
        return context


class ProductsToggleDistributor(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('store:mgmt_product_distributions', args=(kwargs['pslug'],))

    def post(self, *args, **kwargs):
        pslug = kwargs['pslug']
        dslug = kwargs['dslug']
        p = get_object_or_404(Product, slug=pslug)
        d = get_object_or_404(Distributor, slug=dslug)

        if dslug in list(map(lambda d: d.slug, p.distributors.all())):
            p.distributors.remove(d)
        else:
            p.distributors.add(d)

        return super(ProductsToggleDistributor, self).post(*args, **kwargs)


class ProductsUpdate(generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('store:list_products')
    template_name = 'products/update.html'


class ProductsDelete(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('store:list_products')


class OrdersList(generic.ListView):
    template_name = 'orders/index.html'
    context_object_name = 'all_orders'

    def get_queryset(self):
        return Order.objects.all()


class OrdersCreate(generic.CreateView):
    form_class = OrderForm
    success_url = reverse_lazy('store:list_orders')
    template_name = 'orders/create.html'

    def get_form(self, *args, **kwargs):
        if 'product' in self.request.GET:
            product = self.request.GET['product']
            form = OrderForm(product=product)
            return form

        return OrderForm()


class OrdersDetail(generic.DetailView):
    model = Order
    template_name = 'orders/detail.html'
    context_object_name = 'order'


class OrdersUpdate(generic.UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('store:list_orders')
    template_name = 'orders/update.html'


class OrdersDelete(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('store:list_orders')

store/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'store/bootstrap-4.1.2/bootstrap.min.css' %}" />
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% include 'header.html' %}

    {% include 'error_message.html' %}

    {% block content %}
    {% endblock %}
  </div>

  <script src="{% static 'store/jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'store/bootstrap-4.1.2/bootstrap.bundle.min.js' %}"></script>
  {% block js %}
  {% endblock %}
</body>
</html>

store/templates/error_message.html
{% if error_message %}
<div class="alert alert-danger" role="alert">
  {{ error_message }}
</div>
{% endif %}

store/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'store:list_products' %}">iKnowGenome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'store:list_products' %}">产品</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'store:list_orders' %}">订单</a>
      </li>
    </ul>
  </div>
</nav>

store/templates/orders/create.html
{% extends "base.html" %}

{% block title %}创建新订单{% endblock %}

{% block content %}
<h1>创建新订单</h1>
<br>

<form action="{% url 'store:create_order' %}" method="post" class="form-horizontal">
  {% csrf_token %}

  {% if form.errors %}
  <div class="alert alert-danger" role="alert">
    <ul>
      {% for field, errors in form.errors.items %}
        <li>
          {{ field }}: {{ errors|join:", " }}
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% for field in form %}
  <div class="form-group row">
    <label class="col-lg-4 control-label">{{ field.label }}</label>
    <div class="col-lg-8">
      {{ field }}
    </div>
  </div>
  {% endfor %}

  <div class="form-group">
    <button type="submit" class="btn btn-primary">提交</button>
  </div>
</form>
{% endblock %}

{% block js %}
<script type="text/javascript">
  $(function() {
    $('select#id_product').on('change', function() {
      var product = $(this).val();
      window.location.href = "?product=" + product;
    });
  });
</script>
{% endblock %}

store/templates/orders/detail.html
{% extends "base.html" %}

{% block title %}订单({{ order.id }}){% endblock %}

{% block content %}
<h1>{{ order.id }}</h1>

{% endblock %}

store/templates/orders/index.html
{% extends "base.html" %}

{% block title %}订单列表{% endblock %}

{% block content %}
<h1>订单列表 ({{ all_orders|length }})</h1>

<ul>
{% for order in all_orders %}
  <li>
    <a href="{% url 'store:view_order' order.id %}">订单号：{{ order.id }}</a>
    &nbsp;
    <a href="{% url 'store:update_order' order.slug %}">更改</a>
    &nbsp;
    <form action="{% url 'store:delete_order' order.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-link">删除</button>
    </form>
  </li>
{% endfor %}
</ul>

<a href="{% url 'store:create_order' %}">新建</a>
{% endblock %}

store/templates/orders/update.html
{% extends "base.html" %}

{% block title %}订单信息更改{% endblock %}

{% block content %}
<h1>订单信息更改</h1>
<br>

<form action="{% url 'store:update_order' form.instance.id %}" method="post">
  {% csrf_token %}

  {% if form.errors %}
  <div class="alert alert-danger" role="alert">
    <ul>
      {% for field, errors in form.errors.items %}
        <li>
          {{ field }}: {{ errors|join:", " }}
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% for field in form %}
  <div class="form-group row">
    <label class="col-lg-4 control-label">{{ field.label }}</label>
    <div class="col-lg-8">
      {{ field }}
    </div>
  </div>
  {% endfor %}

  <div class="form-group">
    <button type="submit" class="btn btn-primary">提交</button>
  </div>
</form>
{% endblock %}

store/templates/products/create.html
{% extends "base.html" %}

{% block title %}创建新产品{% endblock %}

{% block content %}
<h1>创建新产品</h1>
<br>

<form action="{% url 'store:create_product' %}" method="post" class="form-horizontal">
  {% csrf_token %}

  {% if form.errors %}
  <div class="alert alert-danger" role="alert">
    <ul>
      {% for field, errors in form.errors.items %}
        <li>
          {{ field }}: {{ errors|join:", " }}
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% for field in form %}
  <div class="form-group row">
    <label class="col-lg-4 control-label">{{ field.label }}</label>
    <div class="col-lg-8">
      {{ field }}
    </div>
  </div>
  {% endfor %}

  <div class="form-group">
    <button type="submit" class="btn btn-primary">提交</button>
  </div>
</form>
{% endblock %}

store/templates/products/detail.html
{% extends "base.html" %}

{% block title %}Product ({{ product.slug }}){% endblock %}

{% block content %}
<h1>{{ product.name }}</h1>

<ul>
{% for d in product.distributors.all %}
  <li>{{ d.slug }} - {{ d.name }}</li>
{% endfor %}
</ul>

<a href="{% url 'store:mgmt_product_distributions' product.slug %}">分销商管理</a>
{% endblock %}

store/templates/products/distribution_mgmt.html
{% extends "base.html" %}

{% block title %}Product ({{ product.slug }}) distribution mgmt{% endblock %}

{% block content %}
<strong>已关联分销商：</strong>
{% for d in related_distributors %}
<form action="{% url 'store:toggle_product_distributor' product.slug d.slug %}" method="post">
  {% csrf_token %}
  <input type="checkbox" name="distributor" id="distributor-{{ d.slug }}" value="{{ d.slug }}" onchange="this.form.submit()" checked />
  <label for="distributor-{{ d.slug }}">{{ d.slug }}</label>
  <br />
</form>
{% endfor %}

<strong>未关联分销商：</strong>
{% for d in unrelated_distributors %}
<form action="{% url 'store:toggle_product_distributor' product.slug d.slug %}" method="post">
  {% csrf_token %}
  <input type="checkbox" name="distributor" id="distributor-{{ d.slug }}" value="{{ d.slug }}"  onchange="this.form.submit()" />
  <label for="distributor-{{ d.slug }}">{{ d.slug }}</label>
  <br />
</form>
{% endfor %}

<br>
<br>

<a href="{% url 'store:view_product' product.slug %}">返回产品页</a>
{% endblock %}

store/templates/products/index.html
{% extends "base.html" %}

{% block title %}产品列表{% endblock %}

{% block content %}
<h1>产品列表 ({{ all_products|length }})</h1>

<ul>
{% for product in all_products %}
  <li>
    <a href="{% url 'store:view_product' product.slug %}">{{ product.name }}</a>
    &nbsp;
    <a href="{% url 'store:update_product' product.slug %}">更改</a>
    &nbsp;
    <form action="{% url 'store:delete_product' product.slug %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-link">删除</button>
    </form>
  </li>
{% endfor %}
</ul>

<a href="{% url 'store:create_product' %}">新建</a>
{% endblock %}

store/templates/products/update.html
{% extends "base.html" %}

{% block title %}产品信息更改{% endblock %}

{% block content %}
<h1>产品信息更改</h1>
<br>

<form action="{% url 'store:update_product' form.instance.slug %}" method="post">
  {% csrf_token %}

  {% if form.errors %}
  <div class="alert alert-danger" role="alert">
    <ul>
      {% for field, errors in form.errors.items %}
        <li>
          {{ field }}: {{ errors|join:", " }}
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  {% for field in form %}
  <div class="form-group row">
    <label class="col-lg-4 control-label">{{ field.label }}</label>
    <div class="col-lg-8">
      {{ field }}
    </div>
  </div>
  {% endfor %}

  <div class="form-group">
    <button type="submit" class="btn btn-primary">提交</button>
  </div>
</form>
{% endblock %}